"""upgraded mapping types utc_now and update_at, datetime.utcnow -> datetime.now(timezone.utc)

Revision ID: 14a15097da2a
Revises: 00a717987cd3
Create Date: 2023-11-13 16:55:17.960084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a15097da2a'
down_revision: Union[str, None] = '00a717987cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
