"""added object manager

Revision ID: 1e4c10a5959c
Revises: f534be345a91
Create Date: 2023-11-14 13:59:45.572858

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e4c10a5959c"
down_revision: Union[str, None] = "f534be345a91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "client_tag",
        "obj_id",
        existing_type=sa.INTEGER(),
    )
    op.alter_column(
        "mailing_tag",
        "obj_id",
        existing_type=sa.INTEGER(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mailing_tag", "obj_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "client_tag", "obj_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
