"""fixed

Revision ID: e2bdf217b5cd
Revises: 7c6a71aa112f
Create Date: 2023-11-24 12:18:25.538489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bdf217b5cd'
down_revision: Union[str, None] = '7c6a71aa112f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_tag', 'client_id', new_column_name='obj_id')
    op.alter_column('mailing_tag', 'mailing_id', new_column_name='obj_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_tag', sa.Column('mailing_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mailing_tag', type_='foreignkey')
    op.create_foreign_key('mailing_tag_mailing_id_fkey', 'mailing_tag', 'mailings', ['mailing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mailing_tag', 'obj_id')
    op.add_column('client_tag', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_tag', type_='foreignkey')
    op.create_foreign_key('client_tag_client_id_fkey', 'client_tag', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_tag', 'obj_id')
    # ### end Alembic commands ###
