"""update type datetime

Revision ID: ba20425c1ec3
Revises: 472c9014c53a
Create Date: 2023-11-15 15:26:53.731200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba20425c1ec3'
down_revision: Union[str, None] = '472c9014c53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_tag', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mailing_tag', 'mailing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailing_tag', 'mailing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_tag', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
