"""fixed maooing types

Revision ID: 30471a2461d7
Revises: 8b9aa4e66a9f
Create Date: 2023-11-13 17:26:37.313895

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30471a2461d7"
down_revision: Union[str, None] = "8b9aa4e66a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
