"""update someone

Revision ID: 472c9014c53a
Revises: 1e4c10a5959c
Create Date: 2023-11-14 18:55:33.718144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472c9014c53a'
down_revision: Union[str, None] = '1e4c10a5959c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_tag', sa.Column('client_id', sa.Integer()))
    op.drop_constraint('client_tag_obj_id_fkey', 'client_tag', type_='foreignkey')
    op.create_foreign_key(None, 'client_tag', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_tag', 'obj_id')
    op.add_column('mailing_tag', sa.Column('mailing_id', sa.Integer()))
    op.drop_constraint('mailing_tag_obj_id_fkey', 'mailing_tag', type_='foreignkey')
    op.create_foreign_key(None, 'mailing_tag', 'mailings', ['mailing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mailing_tag', 'obj_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_tag', sa.Column('obj_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mailing_tag', type_='foreignkey')
    op.create_foreign_key('mailing_tag_obj_id_fkey', 'mailing_tag', 'mailings', ['obj_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mailing_tag', 'mailing_id')
    op.add_column('client_tag', sa.Column('obj_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_tag', type_='foreignkey')
    op.create_foreign_key('client_tag_obj_id_fkey', 'client_tag', 'clients', ['obj_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_tag', 'client_id')
    # ### end Alembic commands ###
