"""uninstall lazy strategy

Revision ID: bc55b76de3c7
Revises: 266ed753d9a2
Create Date: 2023-11-11 15:22:25.236912

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc55b76de3c7"
down_revision: Union[str, None] = "266ed753d9a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
