"""create database

Revision ID: d93928c07c45
Revises: 72875a9bfb78
Create Date: 2023-11-10 19:41:49.120258

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d93928c07c45"
down_revision: Union[str, None] = "72875a9bfb78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "status")
    # ### end Alembic commands ###
