name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Files
      run: |
          ls
    - name: Checking with flake8
      run: |
        flake8 --ignore='F821' --per-file-ignores='main.py:F401 tests/conftest.py:E402'
    - name: Create .evn file
      run: |
        touch .test.env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .test.env
        echo MODE=${{ secrets.MODE }} >> .test.env
        echo DRIVER=${{ secrets.DRIVER }} >> .test.env
    - name: Running tests
      run: |
        pytest -vv
