name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: sqlite-latest
        env:
          MODE: TEST
          DRIVER: sqlite+aiosqlite
          DB_NAME: test.db
    env:
      MODE: TEST
      DRIVER: sqlite+aiosqlite
      DB_NAME: test.db
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Files
      run: |
          ls
    - name: Checking with flake8
      run: |
        flake8 --ignore='F821' --per-file-ignores='main.py:F401 tests/conftest.py:E402'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run server
      run: uvicorn main:app --reload
    - name: Up database
      run: alembic upgrade head
    - name: Running tests
      run: pytest -vv --asyncio-mode=auto --python-files='*_tests.py'
